/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary-container": "#9150ac",
        "surface-variant": "#e5e1eb",
        "secondary-fixed": "#d4e3ff",
        "inverse-primary": "#c8bfff",
        "tertiary": "#763792",
        "surface-bright": "#fcf8ff",
        "on-primary-fixed": "#190064",
        "inverse-on-surface": "#f4eff9",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-container": "#003c70",
        "error-container": "#ffdad6",
        "primary-container": "#6a5acd",
        "on-secondary": "#ffffff",
        "surface-dim": "#ddd8e2",
        "on-tertiary-container": "#fce6ff",
        "on-tertiary-fixed-variant": "#692984",
        "outline-variant": "#c9c4d5",
        "surface-container-high": "#ebe6f1",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#004884",
        "on-primary-fixed-variant": "#4532a6",
        "surface-container-low": "#f7f2fc",
        "surface-container-highest": "#e5e1eb",
        "surface-container": "#f1ecf6",
        "surface-tint": "#5d4cbf",
        "primary": "#5140b3",
        "on-background": "#1c1b22",
        "secondary-container": "#65a8fd",
        "secondary": "#005fac",
        "inverse-surface": "#312f37",
        "primary-fixed": "#e5deff",
        "background": "#fcf8ff",
        "on-surface-variant": "#474553",
        "on-tertiary-fixed": "#320047",
        "on-primary-container": "#f0ebff",
        "tertiary-fixed": "#f8d8ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#1c1b22",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001c39",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ebb2ff",
        "surface": "#fcf8ff",
        "outline": "#787584",
        "primary-fixed-dim": "#c8bfff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "base": "4px",
        "margin": "20px",
        "xl": "32px",
        "2xl": "48px",
        "lg": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "title-lg": ["Manrope"],
        "label-md": ["Manrope"],
        "body-md": ["Manrope"],
        "display-lg": ["Manrope"]
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    }
  },
  plugins: [],
}
