"""initial schema

Revision ID: c4bc9c74b1e1
Revises: 
Create Date: 2026-07-25 12:20:26.231303

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c4bc9c74b1e1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
